name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.2  # adjust to your project requirement
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Prepare Hardhat import paths
        run: |
          rm -rf src/lib
          cp -R lib src/lib

      - name: Build
        run: yarn build

      - name: Lint check
        run: yarn lint:check

      - name: Install Foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          source ~/.bashrc
          foundryup

      - name: Run Foundry tests
        run: |
          forge test --match-path test/foundry/Subject.t.sol \
            && forge test --match-path ./test/foundry/Imprint.t.sol
